pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building the app'
                
            }
        }
        stage('Test') {
            steps {
                echo 'Testing the app'
            }
        }
    }
}