pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build - Developement') {
            when {
                branch 'development'
            }
            steps {
                echo 'Building the app in developement branch'

            }
        }
        stage('Build - Production') {
            when {
                branch 'main'
            }
            steps {
                echo 'Building the app in main branch'

            }
        }
        stage('Test') {
            steps {
                echo 'Testing the app'
            }
        }
    }
}