version: 0.2

phases:
  install:
      runtime-versions:
          dotnet: 7.0.0
  pre_build:
    commands:
      - echo Changing directory to root of server application
      - cd server/aspdotnet_main_server
      - ls -al
  build:
    commands:
      - echo Building the ASP.NET Core application in the "build_output" directory, (Linux x64 runtime)
      - dotnet publish -c Release -o ./build_output --runtime linux-x64
  post_build:
    commands:
      - echo Checking the contents of the build_output directory
      - cd build_output
      - ls -al