version: 0.2

phases:
  install:
    commands:
      - wget https://dotnet.microsoft.com/download/dotnet/7.0 -O dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --version 7.0 --install-dir /usr/local/bin/ --runtime dotnet
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore aspdotnet_main_server.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -o ./build_output aspdotnet_main_server.sln
artifacts:
  files:
    - '**/*'
  base-directory: 'build_output'