# Use the official image as a parent image.
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

# Set the working directory.
WORKDIR /app

# Copy the file from your host to your current location.
COPY *.csproj ./

# Run dotnet command to install dependencies.
RUN dotnet restore

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . ./

# Build the application
RUN dotnet publish -c Release -o out