# Use the official image as a parent image.
FROM mcr.microsoft.com/dotnet/aspnet:7.0-focal

# Set the working directory.
WORKDIR /app

# Copy the build output from Dockerfile.build
COPY --from=build-env /app/out .

# Specify the command to run on container start.
ENTRYPOINT ["dotnet", "aspdotnet_main_server.dll"]