version = 0.1
[default.deploy.parameters]
stack_name = "masjid-management-api"
resolve_s3 = false
s3_bucket = "masjid-api-bucket" 
s3_prefix = "masjid-management-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []